### ISSUE TITLE
No proper documentation

### ISSUE THREAD

**Issue by ambs** [melo/docker-dancer2-xslate-starman#1]
While the readme mentioned `melopt/alpine-perl-devel`, the template there uses `build-perl-deps` that is not shipped with this image. Thus, a proper Dockerfile would be welcome, specially if it included details on how to install further modules.

**Comment by melo** [comment]
This image was using a previous Perl base image that was abandoned. I've updated to the latest Perl base image, `melopt/perl-alt`, that includes both proper documentation, Lambda support, and a decent build system.

It is also based on either Alpine or the official Perl docker image, both with 5.36.

The `build-perl-deps` is now `pdi-build-deps`, see the [melopt/perl-alt](https://github.com/melo/docker-perl-alt#perl-docker-image-system) README for more information.
